import { IndianRupee, User, Wallet } from "lucide-react";
export const cardData = [
  {
    icon: User,
    title: "Total Students",
    amount: 10000,
    color: "bg-linear-to-r from-blue-500 to-blue-300"
  },
  {
    icon: Wallet,
    title: "Total Due",
    amount: 20000,
    color: "bg-linear-to-r from-yellow-300 to-orange-400"
  },

  {
    icon: IndianRupee,
    title: "Total Revenue",
    amount: 30000,
    color: "bg-linear-to-r from-green-300 to-green-500"
  }
]

export const students = [
  {
    id: 1,
    name: "Suman Shrestha",
    email: "suman.shrestha@gmail.com",
    password: "suman123",
    class: 10,
    roll: 12,
    academicYear: "2024",
    gender: "Male",
    religion: "Hindu",
    blood: "A+",
    phone: "9841234567",
    totalFee: 50000,
    paidFee: 20000,
    dueFee: 30000,
    status: "pending",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Ramesh Adhikari",
    email: "ramesh.adhikari@gmail.com",
    password: "ramesh123",
    class: 9,
    roll: 5,
    academicYear: "2024",
    gender: "Male",
    religion: "Hindu",
    blood: "B+",
    phone: "9867543210",
    totalFee: 48000,
    paidFee: 30000,
    dueFee: 18000,
    status: "pending",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: 3,
    name: "Bikash Karki",
    email: "bikash.karki@gmail.com",
    password: "bikash123",
    class: 8,
    roll: 18,
    academicYear: "2024",
    gender: "Male",
    religion: "Hindu",
    blood: "O+",
    phone: "9856678899",
    totalFee: 45000,
    paidFee: 45000,
    dueFee: 0,
    status: "paid",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 4,
    name: "Anita Gurung",
    email: "anita.gurung@gmail.com",
    password: "anita123",
    class: 10,
    roll: 7,
    academicYear: "2024",
    gender: "Female",
    religion: "Buddhist",
    blood: "AB+",
    phone: "9812345678",
    totalFee: 52000,
    paidFee: 25000,
    dueFee: 27000,
    status: "pending",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 5,
    name: "Prakash Thapa",
    email: "prakash.thapa@gmail.com",
    password: "prakash123",
    class: 7,
    roll: 3,
    academicYear: "2024",
    gender: "Male",
    religion: "Hindu",
    blood: "B-",
    phone: "9801122334",
    totalFee: 40000,
    paidFee: 15000,
    dueFee: 25000,
    status: "pending",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },

  {
    id: 6,
    name: "Kiran Rai",
    email: "kiran.rai@gmail.com",
    password: "kiran123",
    class: 9,
    roll: 11,
    academicYear: "2024",
    gender: "Male",
    religion: "Kirat",
    blood: "O+",
    phone: "9814455667",
    totalFee: 47000,
    paidFee: 20000,
    dueFee: 27000,
    status: "pending",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 7,
    name: "Sabina Khatri",
    email: "sabina.khatri@gmail.com",
    password: "sabina123",
    class: 8,
    roll: 9,
    academicYear: "2024",
    gender: "Female",
    religion: "Hindu",
    blood: "A-",
    phone: "9863344556",
    totalFee: 43000,
    paidFee: 30000,
    dueFee: 13000,
    status: "pending",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 8,
    name: "Dipesh Bhandari",
    email: "dipesh.bhandari@gmail.com",
    password: "dipesh123",
    class: 10,
    roll: 4,
    academicYear: "2024",
    gender: "Male",
    religion: "Hindu",
    blood: "B+",
    phone: "9851122334",
    totalFee: 52000,
    paidFee: 52000,
    dueFee: 0,
    status: "paid",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 9,
    name: "Nisha Tamang",
    email: "nisha.tamang@gmail.com",
    password: "nisha123",
    class: 7,
    roll: 14,
    academicYear: "2024",
    gender: "Female",
    religion: "Buddhist",
    blood: "O-",
    phone: "9847788990",
    totalFee: 39000,
    paidFee: 20000,
    dueFee: 19000,
    status: "pending",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 10,
    name: "Arjun KC",
    email: "arjun.kc@gmail.com",
    password: "arjun123",
    class: 10,
    roll: 2,
    academicYear: "2024",
    gender: "Male",
    religion: "Hindu",
    blood: "AB-",
    phone: "9812233445",
    totalFee: 55000,
    paidFee: 35000,
    dueFee: 20000,
    status: "pending",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  }
];